### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by PolEpie** [RaphaelIT7/gmod-lua-threaded#1]
Hi, i was interested into looking at your project but idk i got that error even on windows or linux

(PS: I added you on discord)
![image](https://github.com/RaphaelIT7/gmod-lua-threaded/assets/36932762/9e964e2f-212c-4507-af59-4516240bc3c8)

**Comment by RaphaelIT7** [comment]
Hmmmm
I don't get these errors. And the Workflow also doesn't have any issues with the latest version.
Maybe your garrysmod-common is outdated? (I made a PR to update the ILuaObject there which could maybe be the cause?)
(PS: I accepted your friend request)

**Comment by PolEpie** [comment]
So sorry that was my bad i used your gmod common, feel so dumb ahah
